services:
  web:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./data:/data
  worker:
    build: ./backend
    command: celery -A credit_system worker -l info
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./data:/data
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
